server:
  port: 8762
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/githubwsj1996/libraryconfig.git
          username: githubwsj1996
          password: wsj19961221
          search-paths: libraryconfig
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  instance:
      prefer-ip-address: true

